version: '3'

services:
  db:
    container_name: fizzbuzz-hexa-mysql
    image: mysql:${MYSQL_VERSION:-8}
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DB: ${MYSQL_DB:-fizzbuzz}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-user}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - "3306:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
  php-fpm:
    container_name: fizzbuzz-hexa-php-fpm
    build:
      context: ./php-fpm
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=mysql://root:root@db:3306/${MYSQL_DB:-fizzbuzz}?serverVersion=8&charset=utf8
    volumes:
      - ./${APP_FOLDER:-..}/:/var/www/symfony:cached
    ports:
      - '9002:9000'
  nginx:
    container_name: fizzbuzz-hexa-nginx
    build:
      context: ./nginx
    volumes:
      - ./${APP_FOLDER:-..}/:/var/www/symfony
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8088:80"
      - "443:443"